CREATE DATABASE FluffyBakes_DB;
GO

USE FluffyBakes_DB;
GO

CREATE TABLE Products (
	ProductID INT PRIMARY KEY IDENTITY(1,1),
	ProductName NVARCHAR(100) NOT NULL,
	Category NVARCHAR(50) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	QuantityInStock INT NOT NULL
);

CREATE TABLE Customers (
	CustomerID INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(15) NOT NULL
);

CREATE TABLE Orders (
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT NOT NULL, 
	OrderDate DATETIME NOT NULL,
	TotalAmount DECIMAL(10, 2) NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE OrderDetails (
	OrderDetailID INT PRIMARY KEY IDENTITY(1,1),
	OrderID INT NOT NULL,
	ProductID INT NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
	FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

